/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Async byte stream returned by process stdout and stderr.
 *
 * Usage: `for await (const chunk of proc.stdout) process.stdout.write(chunk)`
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class ByteStream {}

/**
 * Running sandbox VM instance.
 *
 * Usage: `const sandbox = await Sandbox.start(); await sandbox.stop()`
 */
export declare class Sandbox {
  /**
   * Boot a new sandbox VM.
   *
   * Usage: `const sandbox = await Sandbox.start({ cpus: 2, mounts: [{ type: 'overlay', hostPath: '.', guestPath: '/workspace' }] })`
   */
  static start(opts?: StartOptions | undefined | null): Promise<Sandbox>
  /**
   * Execute a command and wait for stdout, stderr, and exit code.
   *
   * Usage: `const result = await sandbox.exec('npm test', { cwd: '/workspace' })`
   */
  exec(command: string | Array<string>, opts?: ExecOptions | undefined | null): Promise<ExecResult>
  /**
   * Execute a shell command string with the SDK shell runner.
   *
   * Usage: `const result = await sandbox.execShell('echo $PWD && ls', { cwd: '/workspace' })`
   */
  execShell(command: string, opts?: ExecOptions | undefined | null): Promise<ExecResult>
  /**
   * Start a long-running process with streamable stdout and stderr.
   *
   * Usage: `const proc = await sandbox.spawn(['node', 'server.js'], { cwd: '/workspace' })`
   */
  spawn(
    command: string | Array<string>,
    opts?: SpawnOptions | undefined | null,
  ): Promise<SpawnedProcess>
  /**
   * Watch a guest path for file changes.
   *
   * Usage: `for await (const event of await sandbox.watch('/workspace')) console.log(event.path, event.event)`
   */
  watch(path: string, opts?: WatchOptions | undefined | null): Promise<WatchStream>
  /**
   * Read a guest file as a Buffer.
   *
   * Usage: `const content = await sandbox.readFile('/workspace/package.json')`
   */
  readFile(path: string): Promise<Buffer>
  /**
   * Write a string or Uint8Array to a guest file.
   *
   * Usage: `await sandbox.writeFile('/tmp/input.txt', 'hello')`
   */
  writeFile(path: string, content: string | Uint8Array): Promise<void>
  /**
   * Create a guest directory.
   *
   * Usage: `await sandbox.mkdir('/workspace/out', { recursive: true })`
   */
  mkdir(path: string, opts?: MkdirOptions | undefined | null): Promise<void>
  /**
   * List entries in a guest directory.
   *
   * Usage: `const entries = await sandbox.readDir('/workspace')`
   */
  readDir(path: string): Promise<Array<DirEntry>>
  /**
   * Return metadata for a guest path.
   *
   * Usage: `const stat = await sandbox.stat('/workspace/package.json')`
   */
  stat(path: string): Promise<StatResult>
  /**
   * Remove a guest file or directory.
   *
   * Usage: `await sandbox.remove('/workspace/out', { recursive: true })`
   */
  remove(path: string, opts?: RemoveOptions | undefined | null): Promise<void>
  /**
   * Rename or move a guest file or directory.
   *
   * Usage: `await sandbox.rename('/tmp/a.txt', '/tmp/b.txt')`
   */
  rename(oldPath: string, newPath: string): Promise<void>
  /**
   * Copy a guest file or directory.
   *
   * Usage: `await sandbox.copy('/workspace/src', '/workspace/src-copy', { recursive: true })`
   */
  copy(src: string, dst: string, opts?: CopyOptions | undefined | null): Promise<void>
  /**
   * Change permission bits on a guest path.
   *
   * Usage: `await sandbox.chmod('/workspace/script.sh', 0o755)`
   */
  chmod(path: string, mode: number): Promise<void>
  /**
   * Check whether a guest path exists.
   *
   * Usage: `if (await sandbox.exists('/workspace/package.json')) console.log('found')`
   */
  exists(path: string): Promise<boolean>
  /**
   * Save a named VM checkpoint that can be used with `Sandbox.start({ from })`.
   *
   * Usage: `await sandbox.checkpoint('deps-installed')`
   */
  checkpoint(name: string): Promise<void>
  /**
   * Stop the sandbox VM and release runtime resources.
   *
   * Usage: `await sandbox.stop()`
   */
  stop(): Promise<void>
  /**
   * Absolute host path for this sandbox instance directory.
   *
   * Usage: `console.log(sandbox.instanceDir)`
   */
  get instanceDir(): string
}

/**
 * Handle for a process spawned inside the sandbox.
 *
 * Usage: `const proc = await sandbox.spawn('npm test')`
 */
export declare class SpawnedProcess {
  /**
   * Stream stdout chunks from the spawned process.
   *
   * Usage: `for await (const chunk of proc.stdout) process.stdout.write(chunk)`
   */
  get stdout(): ByteStream
  /**
   * Stream stderr chunks from the spawned process.
   *
   * Usage: `for await (const chunk of proc.stderr) process.stderr.write(chunk)`
   */
  get stderr(): ByteStream
  /**
   * Write data to the process stdin.
   *
   * Usage: `proc.write('hello')`
   */
  write(data: string | Uint8Array): void
  /**
   * Request termination of the process.
   *
   * Usage: `proc.kill()`
   */
  kill(): void
  /**
   * Promise resolving to the process exit code.
   *
   * Usage: `const exitCode = await proc.exited`
   */
  get exited(): Promise<number>
}

/**
 * Async stream of file change events returned by `sandbox.watch`.
 *
 * Usage: `for await (const event of await sandbox.watch('/workspace')) console.log(event.path)`
 *
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class WatchStream {}

/**
 * Download or verify sandbox runtime assets such as kernel, rootfs, and initramfs.
 *
 * Usage: `await initSandbox({ dataDir, force: false })`
 */
export declare function initSandbox(
  opts?: SandboxInitOptions | undefined | null,
): Promise<SandboxInitResult>

/** Options for copying files or directories. */
export interface CopyOptions {
  /** Copy directory trees recursively. Defaults to false. */
  recursive?: boolean
}

/** Directory entry returned by `readDir`. */
export interface DirEntry {
  /** Entry basename. */
  name: string
  /** Entry type such as `file`, `dir`, or `symlink`. */
  type: string
  /** Entry size in bytes. */
  size: number
}

/** Per-command execution options. */
export interface ExecOptions {
  /** Guest working directory. */
  cwd?: string
  /** Additional environment variables. */
  env?: Record<string, string>
  /** Shell used when the command is a string. Defaults to `sh`. */
  shell?: string
}

/** Completed command result. */
export interface ExecResult {
  /** Captured stdout as UTF-8 text. */
  stdout: string
  /** Captured stderr as UTF-8 text. */
  stderr: string
  /** Process exit code. */
  exitCode: number
}

/** Host port made reachable from inside the guest via host.lsb.internal. */
export interface ExposeHostConfig {
  /** Port on the host machine. */
  host: number
  /** Port visible to the guest. Defaults to `host` when omitted. */
  guest?: number
}

/** File watcher event. */
export interface FileChangeEvent {
  /** Changed guest path. */
  path: string
  /** Event kind reported by the guest watcher. */
  event: string
}

/** Options for directory creation. */
export interface MkdirOptions {
  /** Create parent directories as needed. Defaults to true. */
  recursive?: boolean
}

/** Directory mount configuration. */
export interface MountConfig {
  /** Mount behavior: `overlay` isolates writes, `direct` applies libc mount flags. */
  type: 'overlay' | 'direct'
  /** Existing host directory to share with the VM. */
  hostPath: string
  /** Absolute guest path where the directory appears. */
  guestPath: string
  /** libc mount flags for direct mounts. Use `0` for read-write, `1` for MS_RDONLY. */
  flags?: number
}

/** Network policy for a sandbox. */
export interface NetworkConfig {
  /** Outbound host patterns allowed by the proxy. */
  allow?: Array<string>
  /** Host ports exposed to the guest. */
  exposeHost?: Array<ExposeHostConfig>
  /** Secrets injected by the proxy for allowed hosts. */
  secrets?: Record<string, SecretConfig>
}

/** Host-to-guest TCP port forwarding rule. */
export interface PortMappingConfig {
  /** Host port to listen on. */
  host: number
  /** Guest port to forward to. */
  guest: number
}

/** Options for removing files or directories. */
export interface RemoveOptions {
  /** Remove directory trees recursively. Defaults to false. */
  recursive?: boolean
}

/** Runtime asset paths derived from a sandbox data directory. */
export interface SandboxAssetPaths {
  /** Runtime data directory. */
  dataDir: string
  /** VERSION marker path. */
  versionFile: string
  /** Linux kernel image path. */
  kernel: string
  /** Writable root filesystem base image path. */
  rootfs: string
  /** Initramfs image path. */
  initramfs: string
  /** Checkpoint storage directory. */
  checkpointsDir: string
  /** Per-sandbox instance directory root. */
  instancesDir: string
}

/** Options used when initializing sandbox runtime assets. */
export interface SandboxInitOptions {
  /** Runtime data directory. Defaults to `~/.local/share/lsb`. */
  dataDir?: string
  /** Runtime asset version to initialize and pin as a base image. Defaults to this package version. */
  version?: string
  /** Re-download assets even when the expected files and VERSION marker already exist. */
  force?: boolean
}

/** Result returned after initializing or checking sandbox runtime assets. */
export interface SandboxInitResult {
  /** Runtime data directory that was checked or initialized. */
  dataDir: string
  /** Runtime asset version now expected in the data directory. */
  version: string
  /** True when this call downloaded and extracted assets. */
  downloaded: boolean
  /** Concrete runtime asset paths. */
  paths: SandboxAssetPaths
}

/** Secret value that is only exposed to requests for the listed hosts. */
export interface SecretConfig {
  /** Secret payload or source value. */
  value: string
  /** Host allowlist for this secret. */
  hosts: Array<string>
}

/** Options for spawned processes. */
export interface SpawnOptions {
  /** Guest working directory. */
  cwd?: string
  /** Additional environment variables. */
  env?: Record<string, string>
  /** Shell used when the command is a string. Defaults to `sh`. */
  shell?: string
}

/** Options used when booting a sandbox. */
export interface StartOptions {
  /** Stable instance directory name. */
  instanceId?: string
  /** Checkpoint name to resume from. */
  from?: string
  /** Number of virtual CPUs. */
  cpus?: number
  /** Guest memory in MiB. */
  memoryMb?: number
  /** Writable root disk size in MiB. */
  diskSizeMb?: number
  /** Runtime data directory containing VM assets and instances. */
  dataDir?: string
  /** Pinned base runtime asset version to boot from when `from` is not set. Defaults to the initialized VERSION in `dataDir`. */
  baseVersion?: string
  /** Host-to-guest port forwards. */
  ports?: Array<PortMappingConfig>
  /** Directory mounts applied during boot. */
  mounts?: Array<
    | { type: 'overlay'; hostPath: string; guestPath: string }
    | { type: 'direct'; hostPath: string; guestPath: string; flags: number }
  >
  /** Network proxy, host exposure, and secret policy. */
  network?: NetworkConfig
}

/** File metadata returned by `stat`. */
export interface StatResult {
  /** Size in bytes. */
  size: number
  /** POSIX mode bits. */
  mode: number
  /** Modified time as a Unix timestamp in milliseconds. */
  mtime: number
  /** True when the path is a directory. */
  isDir: boolean
  /** True when the path is a regular file. */
  isFile: boolean
  /** True when the path is a symbolic link. */
  isSymlink: boolean
}

/** Options for file watching. */
export interface WatchOptions {
  /** Watch subdirectories recursively. Defaults to true. */
  recursive?: boolean
}
